### ISSUE TITLE
java.lang.NoSuchFieldError: INSTANCE when calling eyes.open(driver, appName, TestName)

### ISSUE THREAD

**Issue by Sikandar-zmx** [applitools/eyes.sdk.java4#34]
implementation ('com.applitools:eyes-appium-java4:4.5.0')

Getting below exception while calling eyes.open(driver, appName, testName)

Exception in thread "main" java.lang.NoSuchFieldError: INSTANCE
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:146)
	at org.glassfish.jersey.apache.connector.ApacheConnector.createConnectionManager(ApacheConnector.java:361)
	at org.glassfish.jersey.apache.connector.ApacheConnector.getConnectionManager(ApacheConnector.java:342)
	at org.glassfish.jersey.apache.connector.ApacheConnector.<init>(ApacheConnector.java:241)
	at org.glassfish.jersey.apache.connector.ApacheConnectorProvider.getConnector(ApacheConnectorProvider.java:116)
	at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:414)
	at org.glassfish.jersey.client.ClientConfig$State.access$000(ClientConfig.java:87)
	at org.glassfish.jersey.client.ClientConfig$State$3.get(ClientConfig.java:119)
	at org.glassfish.jersey.client.ClientConfig$State$3.get(ClientConfig.java:116)
	at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:340)
	at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:722)
	at org.glassfish.jersey.client.ClientRequest.getConfiguration(ClientRequest.java:284)
	at org.glassfish.jersey.client.JerseyInvocation.validateHttpMethodAndEntity(JerseyInvocation.java:126)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:98)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:91)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:424)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:333)
	at com.applitools.eyes.ServerConnector.postWithRetry(ServerConnector.java:435)
	at com.applitools.eyes.ServerConnector.startSession(ServerConnector.java:169)
	at com.applitools.eyes.EyesBase.startSession(EyesBase.java:1675)
	at com.applitools.eyes.EyesBase.ensureRunningSession(EyesBase.java:1417)
	at com.applitools.eyes.EyesBase.openBase(EyesBase.java:1395)
	at com.applitools.eyes.selenium.Eyes.open(Eyes.java:365)
	at com.applitools.eyes.selenium.Eyes.open(Eyes.java:316)

**Comment by danielputerman** [comment]
@Sikandar-zmx For such issues please contact support [at] applitools.com
